# shellcheck disable=SC2148
alias k='kubectl'
alias kgc='kubectl config get-contexts'
alias kuc='kubectl config use-context'
alias kex='kubectl exec -i -t'
alias kg='kubectl get'
alias kgpo='kubectl get pods'
alias kgpoojson='kubectl get pods -o=json'
alias klo='kubectl logs -f'
alias krm='kubectl delete'
