- name: Setting up asdf
  command: ./scripts/asdf.fish
- name: Setting up fish
  command: ./scripts/init.fish
- name: Setting up vim
  command: ./scripts/vim.fish
- name: Setting up osx
  command: ./scripts/osx.fish
