- hosts: localhost
  vars:
    brew_cask_packages:
      - authy
      - diffmerge
      - docker
      - dozer
      - dropbox
      - gitify
      - google-chrome
      - google-cloud-sdk
      - gpg-suitess
      - iterm2
      - java
      - postman
      - pritunl
      - razer-synapse
      - spectacle
      - spotify
      - tunnelblick
      - visual-studio-code
      - vlc
      - whatsapp
    brew_packages:
      - antibody
      - asdf
      - aws-iam-authenticator
      - awscli
      - gssh
      - bat
      - dep
      - eks-login
      - elixir
      - fish
      - fzf
      - gnu-sed
      - golang
      - goreleaser
      - gpg
      - htop
      - httpie
      - httpstat
      - hub
      - hugo
      - jq
      - kube-ps1
      - kubectl
      - kubectx
      - kubernetes-helm
      - kubeseal
      - npm
      - pgcli
      - shellcheck
      - shfmt
      - telnet
      - terminal-notifier
      - terraform
      - terraform-docs
      - terragrunt
      - tokei
      - transmission
      - tree
      - vault
      - wget
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting
    pip_packages:
      - boto
      - google-api-python-client
      - httplib2
      - pgcli
      - pipenv
      - pg_activity
      - uritemplate
  tasks:
    - include: tasks/files.yaml
    - include: tasks/packages.yaml
    - include: tasks/scripts.yaml
    - include: tasks/git.yaml
