- hosts: localhost
  vars:
    brew_cask_packages:
      - authy
      - diffmerge
      - docker
      - dozer
      - dropbox
      - gitify
      - iterm2
      - postman
      - pritunl
      - spectacle
      - spotify
      - tunnelblick
      # - visual-studio-code # TODO: https://github.com/geerlingguy/ansible-role-homebrew/issues/148
      - slack
      - notion
      - whatsapp
      - 1password
    brew_packages:
      - antibody
      - asdf
      - aws-iam-authenticator
      - awscli
      - gssh
      - bat
      - dep
      - fish
      - fzf
      - gnu-sed
      - golang
      - goreleaser
      - gpg
      - htop
      - httpie
      - httpstat
      - hub
      - hugo
      - jq
      - kube-ps1
      - kubectl
      - kubectx
      - kubernetes-helm
      - kubeseal
      - npm
      - pgcli
      - shellcheck
      - shfmt
      - telnet
      - terminal-notifier
      - terraform
      - terraform-docs
      - terragrunt
      - tokei
      - transmission
      - tree
      - vault
      - wget
    pip_packages:
     - pgcli
     - pipenv
     - pg_activity

  tasks:
    - include: tasks/files.yaml
    - include: tasks/packages.yaml
    - include: tasks/scripts.yaml
    - include: tasks/git.yaml
