- hosts: localhost
  vars:
    brew_cask_packages:
      - authy
      - diffmerge
      - docker
      - dropbox
      - google-chrome
      - google-cloud-sdk
      - iterm2
      - pritunl
      - razer-synapse
      - spectacle
      - spotify
      - tunnelblick
      - visual-studio-code
      - vlc
      - whatsapp
    brew_packages:
      - aws-iam-authenticator
      - awscli
      - elixir
      - gnu-sed
      - golang
      - htop
      - hub
      - jq
      - kubectl
      - kubernetes-helm
      - kubeseal
      - npm
      - pgcli
      - shellcheck
      - shfmt
      - telnet
      - terraform
      - terragrunt
      - transmission
      - vault
      - wget
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting
    pip_packages:
      - pgcli
      - boto
  tasks:
    - include: tasks/files.yaml
    - include: tasks/packages.yaml
    - include: tasks/scripts.yaml
    - include: tasks/git.yaml
